### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by HWP97** [jiaw-z/CoR-GS#20]
Hello, I appreciate your great work, CoR-GS.

I have some problems in preparing DTU datasets.
When I operate tools/colmap_dtu.py with scan110(n_views=3), I met some error messages such as,
"No images with matches found in the database."
I wonder if you had some error messages like that.
However, the other scans in DTU dataset scans works fine.

**Comment by jiaw-z** [comment]
Hello, thank you for your interest in CoR-GS. 
When sparse views are used as input, COLMAP may fail due to poor co-visibility relationships between input images. In our tests, this issue can occur in some scenes within the 3-view DTU and 8-view Blender datasets. In these cases, we use random point clouds for initialization (--rand_pcd). We will add related information soon.

**Comment by HWP97** [comment]
Thank you for your quick response!
Your response helped my problems thank you.
